<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Content Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <None Remove="NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.3" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.3" />
    <PackageReference Include="Newtonsoft.Json" Version="7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.Security.Permissions" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="backend\Migrations\" />
    <Folder Include="backend\Configurations\" />
    <Folder Include="frontend\node_modules\" />
    <Folder Include="frontend\src\assets\" />
    <Folder Include="frontend\src\context\" />
    <Folder Include="frontend\src\hooks\" />
    <Folder Include="frontend\src\utils\" />
    <Folder Include="frontend\public\" />
    <Folder Include="test\BackEnd\" />
    <Folder Include="test\FrontEnd\" />
  </ItemGroup>

</Project>
